import type { IndustryModel } from '../services/calculator/types'

export const industryModels: IndustryModel[] = [
  {
    id: 'tea_drink',
    name: '奶茶/饮品',
    icon: '🧋',
    defaultGrossMarginRate: 0.65,
    grossMarginRange: [0.6, 0.7],
    defaultAvgOrderValue: 25,
    avgOrderValueRange: [18, 35],
    defaultBusinessDays: 26,
    defaultRiskLevel: 'warning',
    riskLabel: '中等风险',
    commonFixedCostItems: ['房租', '人工', '水电', '设备'],
    commonExpenseCategories: ['原料', '平台费', '营销', '设备'],
    suggestions: ['优化出品与客流', '提升客单价', '控制固定支出'],
    maxDailyOrders: 120
  },
  {
    id: 'coffee',
    name: '咖啡店',
    icon: '☕',
    defaultGrossMarginRate: 0.7,
    grossMarginRange: [0.65, 0.75],
    defaultAvgOrderValue: 28,
    avgOrderValueRange: [22, 42],
    defaultBusinessDays: 26,
    defaultRiskLevel: 'warning',
    riskLabel: '中等风险',
    commonFixedCostItems: ['房租', '人工', '设备折旧', '水电'],
    commonExpenseCategories: ['原料', '平台费', '营销', '设备'],
    suggestions: ['验证复购频次', '控制租金占比', '用套餐提升客单'],
    maxDailyOrders: 100
  },
  {
    id: 'snack_fastfood',
    name: '小吃快餐',
    icon: '🍔',
    defaultGrossMarginRate: 0.55,
    grossMarginRange: [0.5, 0.6],
    defaultAvgOrderValue: 22,
    avgOrderValueRange: [15, 35],
    defaultBusinessDays: 28,
    defaultRiskLevel: 'warning',
    riskLabel: '中等风险',
    commonFixedCostItems: ['房租', '人工', '水电', '设备'],
    commonExpenseCategories: ['原料', '平台费', '营销', '水电'],
    suggestions: ['先看出餐效率', '控制原料损耗', '复核外卖抽佣'],
    maxDailyOrders: 180
  },
  {
    id: 'bakery',
    name: '烘焙甜品',
    icon: '🧁',
    defaultGrossMarginRate: 0.65,
    grossMarginRange: [0.6, 0.7],
    defaultAvgOrderValue: 32,
    avgOrderValueRange: [20, 55],
    defaultBusinessDays: 26,
    defaultRiskLevel: 'warning',
    riskLabel: '中等风险',
    commonFixedCostItems: ['房租', '人工', '设备折旧', '水电'],
    commonExpenseCategories: ['原料', '营销', '设备', '水电'],
    suggestions: ['控制报损', '提升预订比例', '用组合装提高客单'],
    maxDailyOrders: 90
  },
  {
    id: 'nail_lash',
    name: '美甲美睫',
    icon: '💅',
    defaultGrossMarginRate: 0.75,
    grossMarginRange: [0.7, 0.8],
    defaultAvgOrderValue: 128,
    avgOrderValueRange: [88, 198],
    defaultBusinessDays: 26,
    defaultRiskLevel: 'success',
    riskLabel: '中低风险',
    commonFixedCostItems: ['房租', '人工', '耗材', '平台'],
    commonExpenseCategories: ['耗材', '营销', '平台费', '设备'],
    suggestions: ['提高预约率', '关注技师产能', '控制获客成本'],
    maxDailyOrders: 24
  },
  {
    id: 'pet_store',
    name: '宠物店',
    icon: '🐶',
    defaultGrossMarginRate: 0.5,
    grossMarginRange: [0.45, 0.55],
    defaultAvgOrderValue: 75,
    avgOrderValueRange: [45, 120],
    defaultBusinessDays: 26,
    defaultRiskLevel: 'warning',
    riskLabel: '中等风险',
    commonFixedCostItems: ['房租', '人工', '水电', '设备'],
    commonExpenseCategories: ['原料', '耗材', '营销', '设备'],
    suggestions: ['区分服务和零售毛利', '复核人手配置', '关注复购'],
    maxDailyOrders: 40
  },
  {
    id: 'convenience',
    name: '便利店',
    icon: '🏪',
    defaultGrossMarginRate: 0.25,
    grossMarginRange: [0.2, 0.3],
    defaultAvgOrderValue: 18,
    avgOrderValueRange: [12, 30],
    defaultBusinessDays: 30,
    defaultRiskLevel: 'success',
    riskLabel: '较低风险',
    commonFixedCostItems: ['房租', '人工', '水电', '系统'],
    commonExpenseCategories: ['进货', '水电', '营销', '设备'],
    suggestions: ['关注周转效率', '控制房租比例', '优化高频商品'],
    maxDailyOrders: 220
  },
  {
    id: 'fashion_retail',
    name: '服装零售',
    icon: '👕',
    defaultGrossMarginRate: 0.48,
    grossMarginRange: [0.4, 0.55],
    defaultAvgOrderValue: 168,
    avgOrderValueRange: [99, 299],
    defaultBusinessDays: 28,
    defaultRiskLevel: 'warning',
    riskLabel: '中等风险',
    commonFixedCostItems: ['房租', '人工', '陈列', '平台'],
    commonExpenseCategories: ['进货', '营销', '平台费', '设备'],
    suggestions: ['控制库存深度', '验证客单假设', '关注换季压力'],
    maxDailyOrders: 36
  }
]

export function getIndustryModel(id: string): IndustryModel | undefined {
  return industryModels.find((industry) => industry.id === id)
}
